name: Lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run Prettier
      run: prettier --ignore-path .prettierignore --write .
    - name: Run ESLint
      run: eslint **/*.js --report-unused-disable-directives